### ISSUE TITLE
デプロイ環境構築

### ISSUE THREAD

**Issue by seiichikick0404** [Recursion-Group-B/card-game#10]

**Comment by Tomoya1** [comment]
自動デプロイ設定は料金がかかってしまいそう
運用を考慮する必要がある

**Comment by Tomoya1** [comment]
一旦、developブランチでデプロイ
https://wonderful-crumble-3d7e83.netlify.app/

**Comment by Tomoya1** [comment]
mainブランチにプルリクを流す
