### ISSUE TITLE
deploy 環境を決める

### ISSUE THREAD

**Issue by seiichikick0404** [Recursion-Group-B/card-game#4]

**Comment by Tomoya1** [comment]
> deploy環境の要件
- なるべく楽な環境を選ぶ
- コストなし、どのようなものがあるか調べる

**Comment by Tomoya1** [comment]
> Vercel
- 基本無料で利用できる
- 個人でのGitに統合するのであれば無料
- チームでは[有料](https://vercel.com/pricing)なので、個人で反映する
- 公開が容易
- Githubとの連携ができ、マージごとに反映できそう
- [Qiita](https://qiita.com/yamashin0616/items/b5e9dd03ad88b0e289a1) 記事

**Comment by Tomoya1** [comment]
> Github Pages
- 無料で利用できる
- deployは結局個人で実施なので上記と変わらない
- 公開が容易
- どれも簡単に公開できそう
- バックエンドのサーバーが必要naikara
- 自動デプロイができない
- 一回一回デプロイが必要

**Comment by Tomoya1** [comment]
調査したところ、どれもほぼ一緒

**Comment by Tomoya1** [comment]
deployの楽さは全て変わらないので、本番反映の楽さでいうとVercelかNetlify
Github Pagesは自動デプロイの設定ができないので、自動デプロイ設定ができるのが良さそう

**Comment by Tomoya1** [comment]
今回の規模のプロジェクトではVercelとNetlifyどっちでやっても変わらないが、
Netlifyが自動デプロイの設定が容易にできそうなので、Netlifyでよさそう。
